const statusLabel = document.getElementById("statusLabel");
const riskScore = document.getElementById("riskScore");
const explanation = document.getElementById("explanation");

chrome.storage.local.get("latestAssessment", ({ latestAssessment }) => {
  if (!latestAssessment) {
    explanation.textContent = "No scan result is available yet.";
    return;
  }

  if (latestAssessment.error) {
    statusLabel.textContent = "Backend unavailable";
    explanation.textContent = latestAssessment.error;
    return;
  }

  const percent = Math.round((latestAssessment.risk_score || 0) * 100);
  statusLabel.textContent = latestAssessment.label || "Unknown";
  riskScore.textContent = `${percent}%`;
  explanation.textContent = latestAssessment.used_trained_model
    ? "Prediction generated by the trained ML model."
    : "Prediction generated by the built-in heuristic fallback because no model file is loaded.";
});
